/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 05:33:11 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Queue_ESTest extends Queue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Queue queue0 = new Queue();
      Object object0 = new Object();
      queue0.enqueue(object0);
      int int0 = queue0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Queue queue0 = new Queue();
      queue0.front();
      assertEquals(0, queue0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Queue queue0 = new Queue();
      Object object0 = new Object();
      queue0.enqueue(object0);
      queue0.front();
      assertEquals(1, queue0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Queue queue0 = new Queue();
      queue0.dequeue();
      assertEquals(0, queue0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Queue queue0 = new Queue();
      Object object0 = new Object();
      queue0.enqueue(object0);
      queue0.dequeue();
      assertEquals(0, queue0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Queue queue0 = new Queue();
      int int0 = queue0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Queue queue0 = new Queue();
      Object object0 = new Object();
      queue0.enqueue(object0);
      queue0.enqueue(queue0);
      queue0.dequeue();
      assertEquals(1, queue0.size());
  }
}
