/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 16:07:35 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, (String) null, (String) null);
      boolean boolean0 = appt0.getValid();
      assertTrue(boolean0);
      assertEquals(1, appt0.getStartYear());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1, appt0.getStartHour());
      assertEquals(1, appt0.getStartMinute());
      assertEquals(1, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(4469, 12, 4469, 4469, 12, "qP72pANu", "qP72pANu");
      String string0 = appt0.getTitle();
      assertEquals("qP72pANu", appt0.getDescription());
      assertEquals(4469, appt0.getStartHour());
      assertEquals(4469, appt0.getStartMonth());
      assertEquals(12, appt0.getStartMinute());
      assertEquals("qP72pANu", string0);
      assertEquals(12, appt0.getStartYear());
      assertEquals(4469, appt0.getStartDay());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, (String) null, (String) null);
      int int0 = appt0.getStartYear();
      assertTrue(appt0.getValid());
      assertEquals(1, appt0.getStartHour());
      assertEquals(1, int0);
      assertEquals(1, appt0.getStartDay());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt((-2979), (-2979), (-2979), (-2979), (-2979), (String) null, (String) null);
      int int0 = appt0.getStartYear();
      assertEquals(-2979, appt0.getStartMonth());
      assertEquals(-2979, appt0.getStartMinute());
      assertEquals(-2979, appt0.getStartDay());
      assertEquals((-2979), int0);
      assertEquals(-2979, appt0.getStartHour());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 11, 0, 0, ">)XC01", "@tT-!'*Wr");
      int int0 = appt0.getStartMonth();
      assertEquals(11, appt0.getStartDay());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(">)XC01", appt0.getTitle());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartMinute());
      assertEquals("@tT-!'*Wr", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(257, (-6056), 1006, 1377, 1006, "/", "/");
      int int0 = appt0.getStartMonth();
      assertEquals(1377, int0);
      assertEquals(257, appt0.getStartHour());
      assertEquals("/", appt0.getDescription());
      assertEquals(1006, appt0.getStartDay());
      assertEquals(-6056, appt0.getStartMinute());
      assertEquals("/", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(1006, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 970, 0, (String) null, "1697-02-01T00:00:00Z");
      int int0 = appt0.getStartMinute();
      assertEquals(970, appt0.getStartMonth());
      assertEquals("", appt0.getTitle());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartHour());
      assertEquals("1697-02-01T00:00:00Z", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt(0, (-1), (-1), 59, 0, ":", ":");
      int int0 = appt0.getStartMinute();
      assertEquals((-1), int0);
      assertEquals(":", appt0.getDescription());
      assertEquals(-1, appt0.getStartDay());
      assertEquals(59, appt0.getStartMonth());
      assertEquals(":", appt0.getTitle());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(0, (-264), (-264), (-264), 0, "", "HMS");
      int int0 = appt0.getStartHour();
      assertEquals(-264, appt0.getStartMonth());
      assertEquals(-264, appt0.getStartMinute());
      assertEquals(-264, appt0.getStartDay());
      assertEquals("", appt0.getTitle());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
      assertEquals("HMS", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, Integer.MIN_VALUE, Integer.MIN_VALUE, 2813, (String) null, (String) null);
      int int0 = appt0.getStartHour();
      assertEquals(1, int0);
      assertEquals(-2147483648, appt0.getStartMonth());
      assertEquals(-2147483648, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(1, appt0.getStartMinute());
      assertEquals(2813, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(257, (-6056), 999, 1377, 999, "/", "/");
      appt0.setStartDay(0);
      int int0 = appt0.getStartDay();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, (String) null, (String) null);
      int int0 = appt0.getStartDay();
      assertEquals(1, int0);
      assertEquals(1, appt0.getStartYear());
      assertEquals(1, appt0.getStartHour());
      assertEquals(1, appt0.getStartMinute());
      assertTrue(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt((-681), (-681), (-681), (-681), (-2178), "", "");
      appt0.getDescription();
      assertFalse(appt0.getValid());
      assertEquals(-681, appt0.getStartHour());
      assertEquals(-681, appt0.getStartMonth());
      assertEquals(-681, appt0.getStartDay());
      assertEquals(-2178, appt0.getStartYear());
      assertEquals(-681, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt((-3158), (-3158), (-3158), (-3158), (-3158), "", "+ YbFG");
      assertEquals("+ YbFG", appt0.getDescription());
      
      appt0.setDescription("");
      assertEquals(-3158, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, (-1553), 11, (String) null, "|E7");
      assertEquals("|E7", appt0.getDescription());
      
      appt0.setDescription((String) null);
      assertEquals(11, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt((-3158), (-3158), (-3158), (-3158), (-3158), "", "+ YbFG");
      assertEquals("", appt0.getTitle());
      
      appt0.setTitle("");
      assertEquals(-3158, appt0.getStartHour());
      assertEquals("+ YbFG", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(-3158, appt0.getStartMinute());
      assertEquals(-3158, appt0.getStartDay());
      assertEquals(-3158, appt0.getStartMonth());
      assertEquals(-3158, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 996, 0, (String) null, (String) null);
      appt0.setTitle((String) null);
      assertEquals(996, appt0.getStartMonth());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt(1, 1152, 1, 1, 1, "", "");
      appt0.getTitle();
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1152, appt0.getStartMinute());
      assertEquals(1, appt0.getStartDay());
      assertEquals(1, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(1, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt((-3158), (-3158), (-3158), (-3158), (-3158), "", "+ YbFG");
      int int0 = appt0.getStartDay();
      assertEquals(-3158, appt0.getStartMonth());
      assertEquals("", appt0.getTitle());
      assertEquals(-3158, appt0.getStartYear());
      assertEquals(-3158, appt0.getStartHour());
      assertEquals("+ YbFG", appt0.getDescription());
      assertEquals(-3158, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals((-3158), int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt((-3158), (-3158), (-3158), (-3158), (-3158), "", "+ YbFG");
      boolean boolean0 = appt0.getValid();
      assertEquals(-3158, appt0.getStartHour());
      assertEquals(-3158, appt0.getStartYear());
      assertEquals("+ YbFG", appt0.getDescription());
      assertFalse(boolean0);
      assertEquals(-3158, appt0.getStartMonth());
      assertEquals("", appt0.getTitle());
      assertEquals(-3158, appt0.getStartMinute());
      assertEquals(-3158, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt((-4389), 2199, (-4389), 2199, (-4389), ", ", "pm");
      int int0 = appt0.getStartHour();
      assertFalse(appt0.getValid());
      assertEquals(", ", appt0.getTitle());
      assertEquals(2199, appt0.getStartMinute());
      assertEquals((-4389), int0);
      assertEquals(-4389, appt0.getStartDay());
      assertEquals("pm", appt0.getDescription());
      assertEquals(-4389, appt0.getStartYear());
      assertEquals(2199, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt((-5387), 875, (-5387), 875, 0, "", "r@!7}W^p`=G;");
      int int0 = appt0.getStartYear();
      assertEquals(-5387, appt0.getStartDay());
      assertEquals("", appt0.getTitle());
      assertEquals(875, appt0.getStartMonth());
      assertEquals(-5387, appt0.getStartHour());
      assertEquals(0, int0);
      assertEquals("r@!7}W^p`=G;", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(875, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt((-5387), 875, (-5387), 875, 0, "", "r@!7}W^p`=G;");
      String string0 = appt0.getDescription();
      assertEquals(-5387, appt0.getStartDay());
      assertEquals("", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals("r@!7}W^p`=G;", string0);
      assertEquals(875, appt0.getStartMinute());
      assertEquals(875, appt0.getStartMonth());
      assertEquals(0, appt0.getStartYear());
      assertEquals(-5387, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt((-3158), (-3158), (-3158), (-3158), (-3158), "", "+ YbFG");
      int int0 = appt0.getStartMonth();
      assertEquals(-3158, appt0.getStartHour());
      assertEquals("+ YbFG", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(-3158, appt0.getStartMinute());
      assertEquals((-3158), int0);
      assertEquals(-3158, appt0.getStartDay());
      assertEquals(-3158, appt0.getStartYear());
      assertEquals("", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 23, "Y$,P", "Y$,P");
      appt0.setStartHour(0);
      appt0.toString();
      assertEquals(0, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 23, "Y$,P", "Y$,P");
      String string0 = appt0.toString();
      assertEquals("\t12/23/23 at 11:23pm ,Y$,P, Y$,P\n", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt((-5387), 875, (-5387), 875, 0, "", "r@!7}W^p`=G;");
      appt0.setStartDay(31);
      appt0.setStartHour(11);
      appt0.setStartMinute(59);
      assertEquals(59, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(29, (-1015), (-1015), 0, 29, "h~DM}2T37:Bm^Ewsfz", "h~DM}2T37:Bm^Ewsfz");
      appt0.setStartHour(0);
      appt0.setStartDay(166);
      appt0.setStartMinute(29);
      assertEquals(166, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, (String) null, (String) null);
      appt0.setStartYear((-1511));
      assertEquals(-1511, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, (-1553), 11, (String) null, "|E7");
      String string0 = appt0.toString();
      assertEquals("|E7", appt0.getDescription());
      assertNull(string0);
      assertEquals(-1553, appt0.getStartMonth());
      assertEquals(11, appt0.getStartDay());
      assertEquals(11, appt0.getStartMinute());
      assertEquals(11, appt0.getStartHour());
      assertEquals(11, appt0.getStartYear());
      assertEquals("", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, (-1553), 11, (String) null, "|E7");
      assertEquals(-1553, appt0.getStartMonth());
      
      appt0.setStartMonth(11);
      String string0 = appt0.toString();
      assertEquals("\t11/11/11 at 11:11am ,, |E7\n", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, (-1553), 11, (String) null, "|E7");
      int int0 = appt0.getStartMinute();
      assertEquals(11, appt0.getStartYear());
      assertEquals(11, appt0.getStartHour());
      assertEquals(11, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(-1553, appt0.getStartMonth());
      assertEquals("|E7", appt0.getDescription());
      assertEquals(11, int0);
      assertEquals("", appt0.getTitle());
  }
}
