/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 02:53:50 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.CalendarMain;
import org.evosuite.runtime.System;

public class CalendarMain_ESTest {


}
